name: Upload Node.js 10 and 12 tool cache
on: push
jobs:
  upload_tool_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"
      - name: Setup Node 10
        uses: actions/setup-node@v3
        with:
          node-version: 10.x
      - name: setup-pythons1
        uses: actions/setup-python@v4
        with:
          python-version: '3.6'
      - name: setup-pythons2
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: setup-pythons3
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: setup-pythons4
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: setup-pythons5
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{runner.tool_cache}}/tool_cache.tar.gz
