name: Test an action

on: workflow_dispatch
jobs:
  echo-sth:
    runs-on: ubuntu-latest
    steps:
      - uses: goiPP/echo@master
        with:
          gh_token: secret
  list-emojis:
    runs-on: ubuntu-latest
    steps:
      - name: 'Testing Ruby'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
#       - name: 'list emojis'
#         shell: bash
#         run: |
#           curl -v \
#             -H "Accept: application/vnd.github.v3+json" \
#             -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
#             https://api.github.com/emojis
